export enum QuestionReportReason {
    THE_CORRECT_ANSWER_IS_WRONG = "THE_CORRECT_ANSWER_IS_WRONG",
    MULTIPLE_CORRECT_ANSWERS = "MULTIPLE_CORRECT_ANSWERS",
    QUESTION_UNCLEAR_OR_CONFUSING = "QUESTION_UNCLEAR_OR_CONFUSING",
    SPELLING_OR_GRAMMAR_ERROR = "SPELLING_OR_GRAMMAR_ERROR",
    OUTDATED_INFORMATION = "OUTDATED_INFORMATION",
    OTHER = "OTHER",
}

export enum QuestionReportStatus {
    NEW = "NEW",
    UNDER_REVIEW = "UNDER_REVIEW",
    RESOLVED = "RESOLVED",
    DISMISSED = "DISMISSED",
}
